[package]
name = "personal_site"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
maud = { version = "0.27.0", features = ["rocket"] }
paste = "1.0.15"
pulldown-cmark = "0.13.0"
regex = "1.11.1"
rocket = "0.5.1"
